const PARTICLE_RADIUS = 14;
const SHELL_CAPACITY = [2, 8, 18, 32, 50, 72, 98];
const SHELL_RADII = [85, 165, 255, 355, 470, 600, 745];
const MAX_PROTONS = 118;

const ELEMENT_DATA = [
  null,
  { name: "Hydrogen", symbol: "H" },
  { name: "Helium", symbol: "He" },
  { name: "Lithium", symbol: "Li" },
  { name: "Beryllium", symbol: "Be" },
  { name: "Boron", symbol: "B" },
  { name: "Carbon", symbol: "C" },
  { name: "Nitrogen", symbol: "N" },
  { name: "Oxygen", symbol: "O" },
  { name: "Fluorine", symbol: "F" },
  { name: "Neon", symbol: "Ne" },
  { name: "Sodium", symbol: "Na" },
  { name: "Magnesium", symbol: "Mg" },
  { name: "Aluminum", symbol: "Al" },
  { name: "Silicon", symbol: "Si" },
  { name: "Phosphorus", symbol: "P" },
  { name: "Sulfur", symbol: "S" },
  { name: "Chlorine", symbol: "Cl" },
  { name: "Argon", symbol: "Ar" },
  { name: "Potassium", symbol: "K" },
  { name: "Calcium", symbol: "Ca" },
  { name: "Scandium", symbol: "Sc" },
  { name: "Titanium", symbol: "Ti" },
  { name: "Vanadium", symbol: "V" },
  { name: "Chromium", symbol: "Cr" },
  { name: "Manganese", symbol: "Mn" },
  { name: "Iron", symbol: "Fe" },
  { name: "Cobalt", symbol: "Co" },
  { name: "Nickel", symbol: "Ni" },
  { name: "Copper", symbol: "Cu" },
  { name: "Zinc", symbol: "Zn" },
  { name: "Gallium", symbol: "Ga" },
  { name: "Germanium", symbol: "Ge" },
  { name: "Arsenic", symbol: "As" },
  { name: "Selenium", symbol: "Se" },
  { name: "Bromine", symbol: "Br" },
  { name: "Krypton", symbol: "Kr" },
  { name: "Rubidium", symbol: "Rb" },
  { name: "Strontium", symbol: "Sr" },
  { name: "Yttrium", symbol: "Y" },
  { name: "Zirconium", symbol: "Zr" },
  { name: "Niobium", symbol: "Nb" },
  { name: "Molybdenum", symbol: "Mo" },
  { name: "Technetium", symbol: "Tc" },
  { name: "Ruthenium", symbol: "Ru" },
  { name: "Rhodium", symbol: "Rh" },
  { name: "Palladium", symbol: "Pd" },
  { name: "Silver", symbol: "Ag" },
  { name: "Cadmium", symbol: "Cd" },
  { name: "Indium", symbol: "In" },
  { name: "Tin", symbol: "Sn" },
  { name: "Antimony", symbol: "Sb" },
  { name: "Tellurium", symbol: "Te" },
  { name: "Iodine", symbol: "I" },
  { name: "Xenon", symbol: "Xe" },
  { name: "Cesium", symbol: "Cs" },
  { name: "Barium", symbol: "Ba" },
  { name: "Lanthanum", symbol: "La" },
  { name: "Cerium", symbol: "Ce" },
  { name: "Praseodymium", symbol: "Pr" },
  { name: "Neodymium", symbol: "Nd" },
  { name: "Promethium", symbol: "Pm" },
  { name: "Samarium", symbol: "Sm" },
  { name: "Europium", symbol: "Eu" },
  { name: "Gadolinium", symbol: "Gd" },
  { name: "Terbium", symbol: "Tb" },
  { name: "Dysprosium", symbol: "Dy" },
  { name: "Holmium", symbol: "Ho" },
  { name: "Erbium", symbol: "Er" },
  { name: "Thulium", symbol: "Tm" },
  { name: "Ytterbium", symbol: "Yb" },
  { name: "Lutetium", symbol: "Lu" },
  { name: "Hafnium", symbol: "Hf" },
  { name: "Tantalum", symbol: "Ta" },
  { name: "Tungsten", symbol: "W" },
  { name: "Rhenium", symbol: "Re" },
  { name: "Osmium", symbol: "Os" },
  { name: "Iridium", symbol: "Ir" },
  { name: "Platinum", symbol: "Pt" },
  { name: "Gold", symbol: "Au" },
  { name: "Mercury", symbol: "Hg" },
  { name: "Thallium", symbol: "Tl" },
  { name: "Lead", symbol: "Pb" },
  { name: "Bismuth", symbol: "Bi" },
  { name: "Polonium", symbol: "Po" },
  { name: "Astatine", symbol: "At" },
  { name: "Radon", symbol: "Rn" },
  { name: "Francium", symbol: "Fr" },
  { name: "Radium", symbol: "Ra" },
  { name: "Actinium", symbol: "Ac" },
  { name: "Thorium", symbol: "Th" },
  { name: "Protactinium", symbol: "Pa" },
  { name: "Uranium", symbol: "U" },
  { name: "Neptunium", symbol: "Np" },
  { name: "Plutonium", symbol: "Pu" },
  { name: "Americium", symbol: "Am" },
  { name: "Curium", symbol: "Cm" },
  { name: "Berkelium", symbol: "Bk" },
  { name: "Californium", symbol: "Cf" },
  { name: "Einsteinium", symbol: "Es" },
  { name: "Fermium", symbol: "Fm" },
  { name: "Mendelevium", symbol: "Md" },
  { name: "Nobelium", symbol: "No" },
  { name: "Lawrencium", symbol: "Lr" },
  { name: "Rutherfordium", symbol: "Rf" },
  { name: "Dubnium", symbol: "Db" },
  { name: "Seaborgium", symbol: "Sg" },
  { name: "Bohrium", symbol: "Bh" },
  { name: "Hassium", symbol: "Hs" },
  { name: "Meitnerium", symbol: "Mt" },
  { name: "Darmstadtium", symbol: "Ds" },
  { name: "Roentgenium", symbol: "Rg" },
  { name: "Copernicium", symbol: "Cn" },
  { name: "Nihonium", symbol: "Nh" },
  { name: "Flerovium", symbol: "Fl" },
  { name: "Moscovium", symbol: "Mc" },
  { name: "Livermorium", symbol: "Lv" },
  { name: "Tennessine", symbol: "Ts" },
  { name: "Oganesson", symbol: "Og" },
];

const allElementFacts = [
  {
    atomicNumber: 1,
    symbol: "H",
    name: "Hydrogen",
    fact: "Hydrogen is the most abundant element in the universe, making up roughly 75% of all normal matter. It's the primary fuel for stars like our Sun!",
  },
  {
    atomicNumber: 2,
    symbol: "He",
    name: "Helium",
    fact: "Helium was actually discovered on the Sun before it was found on Earth! Scientists first spotted it by analyzing the light from a solar eclipse in 1868.",
  },
  {
    atomicNumber: 3,
    symbol: "Li",
    name: "Lithium",
    fact: "Lithium is the lightest of all metals. It is so light that it can float on water! Today, it's the crucial ingredient keeping our smartphones and electric cars charged.",
  },
  {
    atomicNumber: 4,
    symbol: "Be",
    name: "Beryllium",
    fact: "Beryllium is practically transparent to X-rays! Because of this unique property, it is used to make the protective windows on X-ray machines.",
  },
  {
    atomicNumber: 5,
    symbol: "B",
    name: "Boron",
    fact: "Boron is the secret ingredient in green fireworks! When burned, boron compounds produce a remarkably bright and distinct emerald green flame.",
  },
  {
    atomicNumber: 6,
    symbol: "C",
    name: "Carbon",
    fact: "Carbon is the foundation of all known life. Depending on how its atoms are arranged, it can be the hardest natural substance (a diamond) or one of the softest (pencil graphite).",
  },
  {
    atomicNumber: 7,
    symbol: "N",
    name: "Nitrogen",
    fact: "Nitrogen makes up a massive 78% of the air we breathe. In its liquid form, it is extremely cold (-196°C) and is used to instantly freeze food and medical samples.",
  },
  {
    atomicNumber: 8,
    symbol: "O",
    name: "Oxygen",
    fact: "While oxygen gas is invisible, liquid and solid oxygen are actually pale blue! Oxygen is also the most abundant element in the Earth's crust.",
  },
  {
    atomicNumber: 9,
    symbol: "F",
    name: "Fluorine",
    fact: "Fluorine is the most reactive of all chemical elements. Pure fluorine gas is so fiercely reactive that it can even burn through glass and water!",
  },
  {
    atomicNumber: 10,
    symbol: "Ne",
    name: "Neon",
    fact: "While we call them all 'neon signs', true neon gas only produces a bright reddish-orange glow. All other colors are created by using different noble gases like Argon or Krypton.",
  },
  {
    atomicNumber: 11,
    symbol: "Na",
    name: "Sodium",
    fact: "Pure sodium is a soft metal you can cut with a butter knife! It violently explodes in water, yet when combined with chlorine, it forms the perfectly safe table salt (NaCl) we eat every day.",
  },
  {
    atomicNumber: 12,
    symbol: "Mg",
    name: "Magnesium",
    fact: "Magnesium burns with an incredibly brilliant white light. Because it is so blindingly bright, it is a key ingredient in emergency flares, sparklers, and fireworks.",
  },
  {
    atomicNumber: 13,
    symbol: "Al",
    name: "Aluminum",
    fact: "Aluminum is infinitely recyclable! Nearly 75% of all the aluminum ever produced in human history is still in use today.",
  },
  {
    atomicNumber: 14,
    symbol: "Si",
    name: "Silicon",
    fact: "Silicon makes up over a quarter of the Earth's crust, mostly in the form of sand and quartz. It is also the foundational element that makes all modern computer chips work!",
  },
  {
    atomicNumber: 15,
    symbol: "P",
    name: "Phosphorus",
    fact: "White phosphorus actually glows in the dark! However, the 'red' version of phosphorus is much more stable and is what you'll find on the striking surface of a matchbox.",
  },
  {
    atomicNumber: 16,
    symbol: "S",
    name: "Sulfur",
    fact: "Sulfur is a bright yellow crystal famous for its terrible smell! When combined with hydrogen, it produces the unmistakable stench of rotten eggs or natural hot springs.",
  },
  {
    atomicNumber: 17,
    symbol: "Cl",
    name: "Chlorine",
    fact: "Chlorine is a pale green gas in its pure form. However, in small, carefully managed amounts, it is incredibly useful for killing bacteria and keeping our swimming pools clean.",
  },
  {
    atomicNumber: 18,
    symbol: "Ar",
    name: "Argon",
    fact: "Argon is a completely unreactive noble gas, making it a perfect protective shield. It is pumped into the space between double-pane windows to insulate homes, and into historical display cases to stop old documents from decaying.",
  },
  {
    atomicNumber: 19,
    symbol: "K",
    name: "Potassium",
    fact: "Potassium is essential for your nervous system and muscle contractions—including your heartbeat! Bananas are famously rich in it. Like sodium, pure potassium metal erupts in purple flames if it touches water.",
  },
  {
    atomicNumber: 20,
    symbol: "Ca",
    name: "Calcium",
    fact: "While we think of calcium as the white mineral that builds our bones, teeth, and seashells, pure elemental calcium is actually a shiny, silvery metal!",
  },
  {
    atomicNumber: 21,
    symbol: "Sc",
    name: "Scandium",
    fact: "Scandium is incredibly light but strong. When mixed with aluminum, it creates high-performance alloys used in aerospace components, high-end bicycle frames, and baseball bats.",
  },
  {
    atomicNumber: 22,
    symbol: "Ti",
    name: "Titanium",
    fact: "Titanium is as strong as steel but 45% lighter! It is also 'biocompatible', meaning the human body doesn't reject it, making it the perfect metal for artificial hips and dental implants.",
  },
  {
    atomicNumber: 23,
    symbol: "V",
    name: "Vanadium",
    fact: "Most of the world's vanadium is mixed with steel to make it practically unbreakable. Henry Ford famously used vanadium steel to build the chassis of the Model T car!",
  },
  {
    atomicNumber: 24,
    symbol: "Cr",
    name: "Chromium",
    fact: "Chromium is the magic ingredient that makes 'stainless' steel rust-resistant. It's also the element that gives rubies their vibrant red color and emeralds their deep green!",
  },
  {
    atomicNumber: 25,
    symbol: "Mn",
    name: "Manganese",
    fact: "Without manganese, there would be no oxygen in the air! It plays a crucial role in photosynthesis, helping plants split water molecules to release oxygen.",
  },
  {
    atomicNumber: 26,
    symbol: "Fe",
    name: "Iron",
    fact: "Iron is the most abundant element making up the Earth, forming almost our entire planetary core. It is also the metal in our blood (hemoglobin) that binds to oxygen, giving blood its red color.",
  },
  {
    atomicNumber: 27,
    symbol: "Co",
    name: "Cobalt",
    fact: "For thousands of years, cobalt has been used to create stunning, deep blue glass and ceramics. Today, you are carrying it in your pocket—it's a critical component in smartphone batteries.",
  },
  {
    atomicNumber: 28,
    symbol: "Ni",
    name: "Nickel",
    fact: "Despite its name, the U.S. 'nickel' coin is actually 75% copper! Nickel is incredibly tough and is one of only four elements that are naturally magnetic at room temperature.",
  },
  {
    atomicNumber: 29,
    symbol: "Cu",
    name: "Copper",
    fact: "Copper is a natural germ-killer! It has strong antimicrobial properties, meaning bacteria and viruses die very quickly when they touch a copper surface.",
  },
  {
    atomicNumber: 30,
    symbol: "Zn",
    name: "Zinc",
    fact: "Zinc's main superpower is sacrificing itself to protect other metals. It is coated over steel (a process called 'galvanization') because the zinc will rust first, keeping the steel perfectly safe beneath it.",
  },
  {
    atomicNumber: 31,
    symbol: "Ga",
    name: "Gallium",
    fact: "Gallium is a metal with a melting point so low (29.7°C or 85.5°F) that a solid spoon made of gallium will literally melt in the palm of your warm hand!",
  },
  {
    atomicNumber: 32,
    symbol: "Ge",
    name: "Germanium",
    fact: "Germanium is a crucial semiconductor. Most of the fiber-optic cables that make the high-speed global internet possible rely on germanium to help guide the light signals!",
  },
  {
    atomicNumber: 33,
    symbol: "As",
    name: "Arsenic",
    fact: "While famous as a historical poison, arsenic was also once used to create a wildly popular, vibrant green dye in the Victorian era—which unfortunately made people wearing it very sick!",
  },
  {
    atomicNumber: 34,
    symbol: "Se",
    name: "Selenium",
    fact: "Selenium is a master of light. Its electrical conductivity increases drastically when exposed to light, making it the hidden secret inside early photocopiers and camera light meters.",
  },
  {
    atomicNumber: 35,
    symbol: "Br",
    name: "Bromine",
    fact: "Bromine is one of only two elements on the entire periodic table (along with Mercury) that is a liquid at room temperature! It is a heavy, reddish-brown liquid with a strong odor.",
  },
  {
    atomicNumber: 36,
    symbol: "Kr",
    name: "Krypton",
    fact: "Superman's home planet shares its name with this real noble gas! On Earth, pure krypton gas is used to create the brilliant white flashes in high-speed photography.",
  },
  {
    atomicNumber: 37,
    symbol: "Rb",
    name: "Rubidium",
    fact: "Rubidium is incredibly reactive and will spontaneously catch fire if exposed to air! Because its atoms vibrate at a highly predictable rate, it is used to build ultra-precise atomic clocks.",
  },
  {
    atomicNumber: 38,
    symbol: "Sr",
    name: "Strontium",
    fact: "If you have ever seen a brilliant, deep red firework explode in the night sky, you are looking at burning strontium!",
  },
  {
    atomicNumber: 39,
    symbol: "Y",
    name: "Yttrium",
    fact: "Before flat screens, heavy, old-school color televisions relied on yttrium to produce the bright red colors on the screen. Today, it's used to make powerful lasers.",
  },
  {
    atomicNumber: 40,
    symbol: "Zr",
    name: "Zirconium",
    fact: "You might know this element as 'cubic zirconia'! When oxidized, zirconium forms a crystal so clear and brilliant that it is the world's most popular diamond substitute.",
  },
  {
    atomicNumber: 41,
    symbol: "Nb",
    name: "Niobium",
    fact: "Niobium becomes a powerful superconductor at low temperatures. It is the critical metal used to build the massive superconducting magnets inside MRI machines!",
  },
  {
    atomicNumber: 42,
    symbol: "Mo",
    name: "Molybdenum",
    fact: "Molybdenum has one of the highest melting points of all pure elements. Because it can withstand extreme heat, it is used to make parts for missiles and jet engines.",
  },
  {
    atomicNumber: 43,
    symbol: "Tc",
    name: "Technetium",
    fact: "Technetium is the very first artificial element ever created! It does not occur naturally on Earth and is highly radioactive, making it incredibly useful as a tracer in medical imaging.",
  },
  {
    atomicNumber: 44,
    symbol: "Ru",
    name: "Ruthenium",
    fact: "Ruthenium is incredibly hard and wear-resistant. If you have ever used an expensive, high-quality fountain pen, the very tip of the nib was likely coated in a ruthenium alloy.",
  },
  {
    atomicNumber: 45,
    symbol: "Rh",
    name: "Rhodium",
    fact: "Rhodium is one of the rarest and most valuable precious metals in the world—often costing much more than gold! It is highly reflective and is used to plate 'white gold' jewelry.",
  },
  {
    atomicNumber: 46,
    symbol: "Pd",
    name: "Palladium",
    fact: "Palladium is like a chemical sponge! It can soak up and absorb 900 times its own volume of hydrogen gas without expanding or changing shape.",
  },
  {
    atomicNumber: 47,
    symbol: "Ag",
    name: "Silver",
    fact: "Of all the metals on the periodic table, silver is the absolute best conductor of electricity and heat! It is the gold standard (pun intended) that all other conductors are measured against.",
  },
  {
    atomicNumber: 48,
    symbol: "Cd",
    name: "Cadmium",
    fact: "For over a century, cadmium was a famous secret ingredient for painters. It was used to create some of the most vibrant and long-lasting yellow, orange, and red pigments in the art world.",
  },
  {
    atomicNumber: 49,
    symbol: "In",
    name: "Indium",
    fact: "You are touching indium right now! When mixed with tin and oxygen, it creates a transparent, electrically conductive coating that makes all modern smartphone touch screens work.",
  },
  {
    atomicNumber: 50,
    symbol: "Sn",
    name: "Tin",
    fact: "Tin has a very strange physical property. If you take a bar of pure solid tin and bend it near your ear, it will literally 'cry' or make a screaming sound as its internal crystals break!",
  },
  {
    atomicNumber: 51,
    symbol: "Sb",
    name: "Antimony",
    fact: "Antimony is one of the few elements (like water) that expands when it freezes! Thousands of years ago, ancient Egyptians used crushed black antimony as the world's first eyeliner, known as kohl.",
  },
  {
    atomicNumber: 52,
    symbol: "Te",
    name: "Tellurium",
    fact: "Tellurium has a very strange side effect on humans. If you touch or breathe in even tiny amounts of it, your body will absorb it and make your breath and sweat smell strongly of pungent garlic for months!",
  },
  {
    atomicNumber: 53,
    symbol: "I",
    name: "Iodine",
    fact: "When heated, solid iodine skips the liquid phase entirely! It 'sublimates' directly from dark, shiny crystals into a thick, beautiful (but toxic) purple gas.",
  },
  {
    atomicNumber: 54,
    symbol: "Xe",
    name: "Xenon",
    fact: "Because Xenon gas is heavy and easily ionized, it is the fuel of choice for 'ion thrusters'—the futuristic engines used to propel modern deep-space probes like NASA's Dawn spacecraft.",
  },
  {
    atomicNumber: 55,
    symbol: "Cs",
    name: "Cesium",
    fact: "Cesium atoms vibrate at an incredibly exact, unchanging rate. Because of this, it is the 'pendulum' inside the world's most accurate atomic clocks, which keep the entire global GPS network synchronized.",
  },
  {
    atomicNumber: 56,
    symbol: "Ba",
    name: "Barium",
    fact: "Barium perfectly blocks X-rays. Doctors often have patients drink a thick, chalky 'barium milkshake' so that their stomach and digestive tract light up perfectly white on an X-ray screen.",
  },
  {
    atomicNumber: 57,
    symbol: "La",
    name: "Lanthanum",
    fact: "Lanthanum is a 'rare-earth' metal that changed photography. Adding it to glass makes the glass highly refractive, which is how professional camera lenses capture crisp, distortion-free images.",
  },
  {
    atomicNumber: 58,
    symbol: "Ce",
    name: "Cerium",
    fact: "If you have ever flicked a standard pocket lighter or used a 'flint and steel' fire starter while camping, the brilliant hot sparks were actually tiny, burning shavings of cerium!",
  },
  {
    atomicNumber: 59,
    symbol: "Pr",
    name: "Praseodymium",
    fact: "Praseodymium is mixed into the special protective glass worn by welders and glassblowers. It completely filters out the blinding yellow glare of the hot flame, protecting their eyes from damage.",
  },
  {
    atomicNumber: 60,
    symbol: "Nd",
    name: "Neodymium",
    fact: "Neodymium is used to forge the strongest permanent magnets in the world! They are so incredibly powerful that two large neodymium magnets snapping together can easily crush human bones.",
  },
  {
    atomicNumber: 61,
    symbol: "Pm",
    name: "Promethium",
    fact: "Promethium is extremely rare and highly radioactive. It is used to make specialized, ultra-long-lasting 'nuclear batteries' for deep space probes and even some medical pacemakers!",
  },
  {
    atomicNumber: 62,
    symbol: "Sm",
    name: "Samarium",
    fact: "Samarium is used to create powerful magnets that can survive extreme, blistering heat without losing their magnetism, making them perfect for the motors of jet fighters and high-end electric guitars.",
  },
  {
    atomicNumber: 63,
    symbol: "Eu",
    name: "Europium",
    fact: "Europium glows brilliantly red or blue under UV light. It is the secret anti-counterfeiting element printed onto Euro banknotes to prove they are real!",
  },
  {
    atomicNumber: 64,
    symbol: "Gd",
    name: "Gadolinium",
    fact: "Gadolinium is incredibly magnetic and reacts strongly to radio waves. Doctors often inject a safe form of it into your veins as a contrast dye to get crystal-clear MRI scans.",
  },
  {
    atomicNumber: 65,
    symbol: "Tb",
    name: "Terbium",
    fact: "Terbium has a strange physical superpower: it physically changes its shape when exposed to a magnetic field! It is used in special devices that can turn solid objects, like tables or glass windows, into giant speakers.",
  },
  {
    atomicNumber: 66,
    symbol: "Dy",
    name: "Dysprosium",
    fact: "Dysprosium is the ultimate sponge for radiation. It easily absorbs loose neutrons, so it is heavily used to make the control rods that prevent nuclear reactors from melting down.",
  },
  {
    atomicNumber: 67,
    symbol: "Ho",
    name: "Holmium",
    fact: "Holmium holds the world record for having the highest magnetic strength of any element! It is used to create highly precise lasers that can perform delicate eye and dental surgeries without damaging surrounding tissue.",
  },
  {
    atomicNumber: 68,
    symbol: "Er",
    name: "Erbium",
    fact: "Without Erbium, the global internet would be incredibly slow. It is added to underwater fiber-optic cables to dramatically boost and amplify the light signals as they travel across the ocean.",
  },
  {
    atomicNumber: 69,
    symbol: "Tm",
    name: "Thulium",
    fact: "Thulium is one of the absolute rarest of the rare-earth metals. When charged up in a nuclear reactor, it becomes the perfect power source for portable, battery-free X-ray machines used in remote areas.",
  },
  {
    atomicNumber: 70,
    symbol: "Yb",
    name: "Ytterbium",
    fact: "Ytterbium is currently being used by scientists to build the next generation of atomic clocks. These new clocks are so precise they wouldn't lose a single second even if they ran for 14 billion years!",
  },
  {
    atomicNumber: 71,
    symbol: "Lu",
    name: "Lutetium",
    fact: "Lutetium is the hardest and heaviest of all the rare-earth metals. It is incredibly expensive to separate and is primarily used to build the sensitive detectors inside medical PET scanners.",
  },
  {
    atomicNumber: 72,
    symbol: "Hf",
    name: "Hafnium",
    fact: "Hafnium is brilliant at absorbing stray electrons. Because of this, it replaced silicon oxide in modern computer chips, allowing companies like Intel to make processors smaller and faster than ever.",
  },
  {
    atomicNumber: 73,
    symbol: "Ta",
    name: "Tantalum",
    fact: "Tantalum is highly immune to the body's internal fluids, making it the perfect metal for surgical staples, pacemakers, and artificial joints. It is also a critical component in your smartphone's battery.",
  },
  {
    atomicNumber: 74,
    symbol: "W",
    name: "Tungsten",
    fact: "Tungsten has the absolute highest melting point of any pure metal on Earth (3,422°C or 6,192°F). It was famously used to make the glowing wire filaments inside old-school incandescent light bulbs.",
  },
  {
    atomicNumber: 75,
    symbol: "Re",
    name: "Rhenium",
    fact: "Rhenium is incredibly dense and heat-resistant. It is heavily mixed with nickel to forge 'superalloys' that can survive the extreme, blistering temperatures inside modern jet turbine engines.",
  },
  {
    atomicNumber: 76,
    symbol: "Os",
    name: "Osmium",
    fact: "Osmium is the single densest naturally occurring element in the universe! A block of osmium is exactly twice as heavy as a block of lead of the exact same size.",
  },
  {
    atomicNumber: 77,
    symbol: "Ir",
    name: "Iridium",
    fact: "Iridium is the most corrosion-resistant metal known to science. A massive layer of it is found worldwide deep underground, proving that a giant asteroid wiped out the dinosaurs 66 million years ago!",
  },
  {
    atomicNumber: 78,
    symbol: "Pt",
    name: "Platinum",
    fact: "Platinum is a precious metal that acts as a powerful chemical catalyst. Most of it is used in the 'catalytic converters' under cars to instantly clean toxic exhaust gases before they leave the tailpipe.",
  },
  {
    atomicNumber: 79,
    symbol: "Au",
    name: "Gold",
    fact: "Gold is the most malleable metal on Earth. A single ounce of gold can be beaten into a flat sheet measuring roughly 300 square feet, or drawn into a wire over 50 miles long!",
  },
  {
    atomicNumber: 80,
    symbol: "Hg",
    name: "Mercury",
    fact: "Mercury is the only metal that is completely liquid at room temperature! While it looks like beautiful, heavy silver water, its vapors are incredibly toxic to the human brain and nervous system.",
  },
  {
    atomicNumber: 81,
    symbol: "Tl",
    name: "Thallium",
    fact: "Thallium is incredibly toxic and completely tasteless and odorless. Because of this, it was famously known as 'The Poisoner's Poison' and was frequently used by villains in Agatha Christie murder mystery novels!",
  },
  {
    atomicNumber: 82,
    symbol: "Pb",
    name: "Lead",
    fact: "Lead is incredibly heavy and dense, making it the perfect shield against radiation. It is the metal used to make the heavy aprons dentists put over your chest before taking an X-ray of your teeth.",
  },
  {
    atomicNumber: 83,
    symbol: "Bi",
    name: "Bismuth",
    fact: "When bismuth is melted and cooled, it forms mind-blowing, perfectly square, iridescent 'staircase' crystals! It is also the main soothing ingredient in pink stomach medicines like Pepto-Bismol.",
  },
  {
    atomicNumber: 84,
    symbol: "Po",
    name: "Polonium",
    fact: "Polonium is a highly radioactive metal discovered by the famous scientist Marie Curie. She named it after her home country of Poland to bring attention to its fight for independence!",
  },
  {
    atomicNumber: 85,
    symbol: "At",
    name: "Astatine",
    fact: "Astatine is the rarest naturally occurring element on Earth! It is so unstable that scientists estimate there is less than one single ounce of it existing inside the entire Earth's crust at any given moment.",
  },
  {
    atomicNumber: 86,
    symbol: "Rn",
    name: "Radon",
    fact: "Radon is a heavy, invisible, highly radioactive gas. Because it is heavier than air, it naturally seeps up from the ground and can secretly accumulate in the dark basements of old houses.",
  },
  {
    atomicNumber: 87,
    symbol: "Fr",
    name: "Francium",
    fact: "If you threw a chunk of francium into water, it would create an explosion vastly more violent than sodium or potassium! However, it is so incredibly rare and radioactive that a visible chunk has never actually been assembled.",
  },
  {
    atomicNumber: 88,
    symbol: "Ra",
    name: "Radium",
    fact: "Because radium is so radioactive, it actually glows in the dark! In the early 1900s, it was painted onto the hands of watches so people could read the time at night, before scientists realized how dangerous it was.",
  },
  {
    atomicNumber: 89,
    symbol: "Ac",
    name: "Actinium",
    fact: "Actinium gives its name to the entire 'Actinide' row at the bottom of the periodic table. It is so intensely radioactive that it literally glows with a spooky, pale blue light in the dark!",
  },
  {
    atomicNumber: 90,
    symbol: "Th",
    name: "Thorium",
    fact: "Named after Thor, the Norse god of thunder! Thorium is slightly radioactive and is currently being researched by scientists as a much safer, cleaner alternative to uranium for fueling next-generation nuclear power plants.",
  },
  {
    atomicNumber: 91,
    symbol: "Pa",
    name: "Protactinium",
    fact: "Protactinium is one of the rarest and most expensive naturally occurring elements on Earth. It is so scarce that scientists once had to process over 60 tons of radioactive dirt just to extract 125 grams of it!",
  },
  {
    atomicNumber: 92,
    symbol: "U",
    name: "Uranium",
    fact: "Uranium packs an unbelievable amount of power. A single pellet of uranium the size of a gummy bear contains the exact same amount of energy as 120 gallons of oil or 1 ton of coal!",
  },
  {
    atomicNumber: 93,
    symbol: "Np",
    name: "Neptunium",
    fact: "Following the naming trend of planets, Neptunium was named after the planet Neptune because it comes right after Uranium on the periodic table!",
  },
  {
    atomicNumber: 94,
    symbol: "Pu",
    name: "Plutonium",
    fact: "While famous for nuclear weapons, a special type of Plutonium is the ultimate space battery! It generates intense heat that powers deep-space probes like the Voyager spacecraft and the Mars Perseverance rover.",
  },
  {
    atomicNumber: 95,
    symbol: "Am",
    name: "Americium",
    fact: "You probably have this radioactive element in your house right now! A microscopic amount of Americium is used inside almost every standard household smoke detector to sense smoke particles in the air.",
  },
  {
    atomicNumber: 96,
    symbol: "Cm",
    name: "Curium",
    fact: "Named after the legendary scientists Marie and Pierre Curie! Curium is so fiercely radioactive that a chunk of it gets so hot it will literally boil water just by sitting in it.",
  },
  {
    atomicNumber: 97,
    symbol: "Bk",
    name: "Berkelium",
    fact: "This element is named after the city of Berkeley, California. The scientists at the University of California, Berkeley discovered a staggering 16 different elements on the periodic table!",
  },
  {
    atomicNumber: 98,
    symbol: "Cf",
    name: "Californium",
    fact: "Californium is one of the single most expensive materials on the planet! Because it is incredibly difficult to synthesize, a single gram of it can cost over $25 million.",
  },
  {
    atomicNumber: 99,
    symbol: "Es",
    name: "Einsteinium",
    fact: "Named in honor of the genius Albert Einstein! This element wasn't discovered in a lab—it was first found hidden in the radioactive fallout debris of the world's very first hydrogen bomb test in 1952.",
  },
  {
    atomicNumber: 100,
    symbol: "Fm",
    name: "Fermium",
    fact: "Also discovered in the debris of the first hydrogen bomb! Fermium marks a massive milestone: it is the absolute heaviest element that can be created by firing neutrons at lighter elements.",
  },
  {
    atomicNumber: 101,
    symbol: "Md",
    name: "Mendelevium",
    fact: "Named in honor of Dmitri Mendeleev, the brilliant chemist who invented the modern periodic table and successfully predicted the existence of elements that hadn't even been discovered yet!",
  },
  {
    atomicNumber: 102,
    symbol: "No",
    name: "Nobelium",
    fact: "Named after Alfred Nobel, the inventor of dynamite. He used his massive fortune to establish the Nobel Prize to honor humanity's greatest achievements in science and peace.",
  },
  {
    atomicNumber: 103,
    symbol: "Lr",
    name: "Lawrencium",
    fact: "Named after Ernest Lawrence, the inventor of the 'cyclotron.' This massive circular machine revolutionized physics by allowing scientists to smash atoms together to create brand new elements.",
  },
  {
    atomicNumber: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    fact: "Named after Ernest Rutherford, who famously discovered that atoms are mostly empty space with a tiny, dense nucleus in the center—the exact concept your ChemGL app is visualizing!",
  },
  {
    atomicNumber: 105,
    symbol: "Db",
    name: "Dubnium",
    fact: "Named after the town of Dubna in Russia, which is home to the Joint Institute for Nuclear Research. This facility is responsible for discovering some of the heaviest elements in the universe.",
  },
  {
    atomicNumber: 106,
    symbol: "Sg",
    name: "Seaborgium",
    fact: "This element caused massive drama! It was named after American chemist Glenn T. Seaborg while he was still alive, which broke a long-standing unwritten rule in the scientific community.",
  },
  {
    atomicNumber: 107,
    symbol: "Bh",
    name: "Bohrium",
    fact: "Named after Niels Bohr, the legendary physicist who proposed the 'Bohr model' of the atom—which is exactly what your interactive canvas is drawing with its central nucleus and orbiting electron shells!",
  },
  {
    atomicNumber: 108,
    symbol: "Hs",
    name: "Hassium",
    fact: "Named after the German state of Hesse. Because it is so heavy and decays so incredibly fast, scientists have only ever managed to create a few dozen atoms of Hassium in all of human history.",
  },
  {
    atomicNumber: 109,
    symbol: "Mt",
    name: "Meitnerium",
    fact: "Named to honor Lise Meitner, a brilliant physicist who was one of the first to discover nuclear fission. She famously had to flee Germany during WWII and do her calculations in secret.",
  },
  {
    atomicNumber: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    fact: "To create just a single atom of Darmstadtium, scientists had to fire billions of nickel atoms at a target of lead for days on end inside a massive particle accelerator.",
  },
  {
    atomicNumber: 111,
    symbol: "Rg",
    name: "Roentgenium",
    fact: "Named after Wilhelm Röntgen, the scientist who accidentally discovered X-rays in 1895 when a glowing green light suddenly appeared across his dark laboratory!",
  },
  {
    atomicNumber: 112,
    symbol: "Cn",
    name: "Copernicium",
    fact: "Named after Nicolaus Copernicus, the astronomer who first proposed that the Earth orbits the Sun—just like how electrons orbit the nucleus in your ChemGL app!",
  },
  {
    atomicNumber: 113,
    symbol: "Nh",
    name: "Nihonium",
    fact: "Nihonium is the very first element on the periodic table to be discovered in an Asian country! 'Nihon' is one of the two ways to say 'Japan' in Japanese.",
  },
  {
    atomicNumber: 114,
    symbol: "Fl",
    name: "Flerovium",
    fact: "Scientists suspect Flerovium might sit near an 'Island of Stability'—a theoretical zone on the periodic table where superheavy elements might actually exist for years instead of just split-seconds.",
  },
  {
    atomicNumber: 115,
    symbol: "Mc",
    name: "Moscovium",
    fact: "Named after the Moscow region in Russia, where the element was first synthesized. It decays so quickly into other elements that it is practically impossible to study its chemical properties.",
  },
  {
    atomicNumber: 116,
    symbol: "Lv",
    name: "Livermorium",
    fact: "Named after the Lawrence Livermore National Laboratory in California. The lab teamed up with Russian scientists to smash Calcium and Curium together to create this fleeting element.",
  },
  {
    atomicNumber: 117,
    symbol: "Ts",
    name: "Tennessine",
    fact: "Named after the US state of Tennessee. It is the second-heaviest element ever created, and scientists had to ship highly radioactive materials back and forth across the ocean just to synthesize it.",
  },
  {
    atomicNumber: 118,
    symbol: "Og",
    name: "Oganesson",
    fact: "This is it—the absolute heaviest element currently known to humanity! Named after physicist Yuri Oganessian, it completes the 7th row of the periodic table. Scientists are now hunting for element 119!",
  },
];
